### ISSUE TITLE
Unable to update Trigger parameters from CLI

### ISSUE THREAD

**Issue by eweiter** [apache/openwhisk-cli#290]
When inspecting the `wsk trigger update <trigger-name>` command it was shown that you can specify a `-p` to update parameters. 

When I tried to do this it failed with a response mentioning
""error": "no updatable parameters were specified""

Upon inspecting the command with a `-v` it is revealed that when the update command calls a POST to the Feed it is getting back a 502 error.  Something about this 502 error is causing it to not update the Trigger.

**Comment by dubee** [comment]
@mdeuser, @csantanapr, @drcariel, @abaruni

**Comment by abaruni** [comment]
@eweiter could you provide a little bit of context? i.e. the feed you're working with, the command you're running, the target region, etc

**Comment by dubee** [comment]
Related to https://github.com/apache/incubator-openwhisk-wskdeploy/issues/884#issuecomment-386106835.

**Comment by eweiter** [comment]
So one proposal for how to handle this would be the introduction of a new parameter, something like --feed-param/-fp , that would indicate the following:
a) If I see --param/-p , I update the Trigger's parameter
b) If I see --feed-param/-fp, I update the Feed's parameter

This issue has relations to an issue with the GET command `wsk trigger get <trigger_name>` and the create command `wsk trigger create <trigger_name>`.  I will be opening up separate issues and adding them as references.

**Comment by abaruni** [comment]
my proposal here would be to not mix the concepts of a feed and a trigger and have a separate whisk entity for feeds. then something like `wsk feed create <feed_name> /whisk.system/some-feed/feed -p trigger <trigger_name> -p feed_param val` could be useed. and `wsk trigger get`, `wsk trigger update mytrigger -p foo bar` would not collide with `wsk feed get`, `wsk feed update myfeed -p feed_specific_parameter val`
