### ISSUE TITLE
Is there some way to run `wsk` on Apple m1 chip?

### ISSUE THREAD

**Issue by GitHubDiom** [apache/openwhisk-cli#511]
Hi, there

I am trying to devolpe openwhisk in my Apple M1 laptop, and I need to install `wsk` to interact with the openwhisk.

At the beginning, I have installed the AMD64 version of `wsk` and I found that it is not helpful for the local testing.

The "M1" version doesn't seem ready for release yet, is there any way to test my openwhisk local?

Thankyou

**Comment by rabbah** [comment]
Hi @GitHubDiom did this work?

**Comment by GitHubDiom** [comment]
> Hi @GitHubDiom did this work?

yeah brew install wsk works fine
